version: "3.9"  # optional since v1.27.0

networks:
  development:
    driver: bridge

services:
  spending-tracker_web-app:
    build:
      context: .
    container_name: spending-tracker_web-app
    image: avemepls/spending-tracker_web-app:latest
    ports:
      - "80:80"
    depends_on:
      - spending-tracker_web-api

  spending-tracker_web-api:
    build:
      context: .
    container_name: spending-tracker_web-api
    image: avemepls/spending-tracker_web-api:latest
    ports:
      - "5000:5000"
    depends_on:
      - spending-tracker_db2
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION-STRINGS_SPENDING-TRACKER-DB: "Server=spending-tracker_db2;Port=5432;Database=SpendingTracker;Username=postgres;Password=postgres"
      SYSTEM-USER-CONTEXT-OPTIONS_CACHE-ABSOLUTE-EXPIRATION-RELATIVE-TO-NOW: "00:30:00"
      TELEGRAM-USER-CONTEXT-OPTIONS_CACHE-ABSOLUTE-EXPIRATION-RELATIVE-TO-NOW: "00:30:00"
      OAUTH-OPTIONS_SECRET-KEY: "1EDBF1AEC985367A1F280491A844FA0C06FAFF32A82CDD0713B2B2AC70096701"
      OAUTH-OPTIONS_SECRET-ISSUER: "SpendingTracker"
      OAUTH-OPTIONS_ACCESS-TOKEN-LIFETIME-IN-MINUTES: 150
      CORS-OPTIONS_ORIGINS: "http://127.0.0.1"
    networks:
      - development

  spending-tracker_db2:
    container_name: spending-tracker_db2
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SpendingTracker
    networks:
      - development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: